name: 'GitHub commit emailer'
description: 'Send emails whenever a push event happens'

inputs:
  host:
    required: true
    type: string
  port:
    required: true
    type: string
  from:
    required: true
    type: string
  to:
    required: true
    type: string
  password:
    required: true

runs:
  using: 'composite'
  steps:
    - run: brew install aha git-delta
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        cache: false
    - run: go build ${{ github.action_path }}/mailbot.go
      shell: bash
    - run: ./mailbot
      shell: bash
      env:
        MAILBOT_HOST: ${{ inputs.host }}
        MAILBOT_PORT: ${{ inputs.port }}
        MAILBOT_FROM: ${{ inputs.from }}
        MAILBOT_TO: ${{ inputs.to }}
        MAILBOT_PASSWORD: ${{ inputs.password }}
        MAILBOT_GH_EVENT: ${{ toJSON(github.event) }}
