name: 'GitHub commit emailer'
description: 'Send emails whenever a push event happens'

inputs:
  host:
    required: true
    type: string
  port:
    required: true
    type: string
  from:
    required: true
    type: string
  to:
    required: true
    type: string
  password:
    required: true

runs:
  using: "composite"
  steps:
    - run: ls -lR ${{ github.action_path }}
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      cache: false
    - run: go run main.go
      shell: bash
      env:
        MAILBOT_HOST: ${{ inputs.host }}
        MAILBOT_PORT: ${{ inputs.port }}
        MAILBOT_FROM: ${{ inputs.from }}
        MAILBOT_TO: ${{ inputs.to }}
        MAILBOT_PASSWORD: ${{ inputs.password }}
        MAILBOT_GH_EVENT: ${{ toJSON(github.event) }}
