name: GitHub commit emailer

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      port:
        required: true
        type: string
      from:
        required: true
        type: string
      to:
        required: true
        type: string
    secrets:
      password:
        required: true

jobs:
  emailer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v5
      - run: go run main.go
        env:
          MAILBOT_HOST: ${{ inputs.host }}
          MAILBOT_PORT: ${{ inputs.port }}
          MAILBOT_FROM: ${{ inputs.from }}
          MAILBOT_TO: ${{ inputs.to }}
          MAILBOT_PASSWORD: ${{ secrets.password }}
